In [1]:
 import torch
 from einops import rearrange, reduce, repeat, einsum

## einops2

In [9]:
x = torch.ones(3, 4)  # seq1 hidden
y = torch.ones(4, 3)  # hidden seq2
# Old way
z = x @ y   # seq1 seq2
# New (einops) way
z = einsum(x, y, "seq1 hidden1, hidden1 seq2 -> seq1 seq2")

In [8]:
x, y, z

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[16., 16., 16.],
         [16., 16., 16.],
         [16., 16., 16.]]))

In [3]:
z

tensor([[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]])